crudstudent/crudstudent/urls.py
from django.contrib import admin
from django.urls import path
from students import views  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('add/', views.add,name='add'),
    path('show/',views.show,name='show'),
    path('delete/<int:id>', views.delete,name='delete'),
    path('login/',views.login,name="login"),


]

crudstudent/students/urls.py
#urlpatterns = [
#    path('admin/',admin.site.urls),
#    path('stu',views.stu),
#    path('show',views.show),
#    path('edit/<int:id>',views.edit)
#]

crudstudent/students/models.py
from django.db import models

# Create your models here.

class Student(models.Model):

    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    email = models.EmailField()
    econtact = models.CharField(max_length=15)

    class Meta:
        db_table="ajeet"

crudstudent/students/forms.py
from dataclasses import field
from django import forms
from students.models import Student
class StudentForms(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

crudstudent/students/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from students.forms import StudentForms
from students.models import Student

from students.forms import StudentForms

# Create your views here.
def add(request):
    print("in stu funcaton is calling ")
    if request.method == 'POST':
        print("Inside POST Methord  ")
        form = StudentForms(request.POST)
        print("Inside POST Methord request ")
        if form.is_valid():
            print(">>>> valid  ")
            form.save()
            print(">>>> save  ")
            return redirect('/show')
    form=StudentForms()
    return render(request,'index.html',{'form': form})




def show(request):
    students = Student.objects.all()
    return render(request,'show.html',{'students':students})


#Edit Function

def edit(request,id):
    student =Student.objects.get(id=id)

    return render(request,'edit.html',{'student':student})

#Login function
def login(request):
    return render(request,'login.html')

def delete(request,id):
    student = Student.objects.get(id=id)
    student.delete()
    return redirect(request,'show.html')

crudstudent/students/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

crudstudent/students/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{student.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ student.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">student Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ student.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">student Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ student.eemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">student Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ student.econtact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

crudstudent/students/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Index</title>
        {% load static %}  
        <link rel="stylesheet" href="{% static 'style.css' %}"/>  
        
    </head>
    <body>  
        <form method="POST" class="post-form" action="/add/">  
                {% csrf_token %}  
            <div class="container">  
        <br>  
            <div class="form-group row">  
            <label class="col-sm-1 col-form-label"></label>  
            <div class="col-sm-4">  
            <h3>Enter Details</h3>  
            </div>  
          </div>  
            <div class="form-group row">  
            <label class="col-sm-2 col-form-label">Student Id:</label>  
            <div class="col-sm-4">  
              {{ form.eid }}  
            </div>
          </div>  
          <div class="form-group row">  
            <label class="col-sm-2 col-form-label">Student Name:</label>  
            <div class="col-sm-4">  
              {{ form.ename }}  
            </div>  
          </div>  
            <div class="form-group row">  
            <label class="col-sm-2 col-form-label">Student Email:</label>  
            <div class="col-sm-4">  
              {{ form.email }}  
            </div>  
          </div>  
            <div class="form-group row">  
            <label class="col-sm-2 col-form-label">Student Contact:</label>  
            <div class="col-sm-4">  
              {{ form.econtact }}  
            </div>  
          </div>  
            <div class="form-group row">  
            <label class="col-sm-1 col-form-label"></label>  
            <div class="col-sm-4">  
            <button type="submit" class="btn btn-primary">Submit</button>  
            </div>  
          </div>  
            </div>  
        </form>  
        </body>  
        </html>  

crudstudent/students/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Signin Template · Bootstrap v5.1</title>
     
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>  
    <link rel="stylesheet" href="{% static 'css/Signin.css' %}" />

    <!-- Bootstrap core CSS 
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
-->
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
   
  </head>
  <body class="text-center">
    
<main class="form-signin">
  <form>
    <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
  </form>
</main>


    
  </body>
</html>

crudstudent/students/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Student ID</th>
        <th>Student Name</th>
        <th>Student Email</th>
        <th>Student Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for student in students %}
    <tr>
        <td>{{ student.eid }}</td>
        <td>{{ student.ename }}</td>
        <td>{{ student.eemail }}</td>
        <td>{{ student.econtact }}</td>
        <td>
            <a href="/edit/{{ student.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ student.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/add" class="btn btn-primary">Add New Record</a></center>
</body>  
</html>  